### ISSUE TITLE
Are you a big deal ? :)

### ISSUE THREAD

**Issue by rnjailamba** [tunnckoCore/ama#10]

**Comment by tunnckoCore** [comment]
Hi!

What you mean with "_big deal_"? I'm big deal in some aspects, in other i'm "low deal", lol.
I can say yes, and no. I'm just super passionate developer, currently on node land, currently in node community and i'm very glad that i'm part of it – as I tweeted [„When you are part of JavaScript, you are part of anything - part of the Universe“](https://twitter.com/tunnckoCore/status/698284915348107264).

[![screenshot from 2016-03-20 00-37-07](https://cloud.githubusercontent.com/assets/5038030/13901674/0c0a4748-ee34-11e5-8dd1-7f35498ed043.png)](https://twitter.com/tunnckoCore/status/698284915348107264)

I'm big deal in writing, philosophy, logic, abstract thinking and writing quality code.

**Comment by rnjailamba** [comment]
hahaha
interesting to know!
it was actually the first time i had seen someone with a repository for ama so just thought of poking you.
