### ISSUE TITLE
/messages redirect?

### ISSUE THREAD

**Issue by FezVrasta** [tunnckoCore/ama#11]
Hi, sorry to bother you, but I've a question 🙂

I see that visiting https://github.com/tunnckoCore/messages I get redirected to https://github.com/tunnckoCore/ama

How this redirect works?

Thanks!

**Comment by tunnckoCore** [comment]
Hi. Initially it that repo just was called `messages`. I didn't do anything :D

**Comment by FezVrasta** [comment]
Ahh I see, lol. Thanks
