### ISSUE TITLE
When will you run add-owners.js?

### ISSUE THREAD

**Issue by RobLoach** [tunnckoCore/ama#2]
JSTransformers needs your help. It has been more than 3 months on some projects. When will you run [Nuke's add-owners.js](https://github.com/jstransformers/nuke/blob/master/add-owners.js)?

https://github.com/jstransformers/nuke/issues/7#issuecomment-114174047

**Comment by tunnckoCore** [comment]
Doh, yea sorry. Im coming tonight. Also if you noticed today i forked `ownership` repo, which looks awesome and exactly what we need :) 

btw can you send PR for this my repo to `sindresorhus/amas`, please? :D 

Guess why im asking you, huh. :dancers:  lol

**Comment by RobLoach** [comment]
> i forked ownership repo, which looks awesome and exactly what we need :)

I've put up a PR at https://github.com/jstransformers/ownership/pull/1 which demonstrates that it's missing a couple things. What we need is the permissions on npm so that the packages are not broken. We need you to run add-owners.js .
