### ISSUE TITLE
Why did Sindre unblock you?

### ISSUE THREAD

**Issue by stevemao** [tunnckoCore/ama#8]

**Comment by tunnckoCore** [comment]
When? I'm blocked again, currently. He blocked me again (i can repeat myself again, there's no reason, or I can't see it) one-two weeks after he unblocked me. Nevermind.
I totally don't understand why he blocking me, I don't have contact with him.
It was good that he accepted my PR for my AMA on `sindresorhus/amas` in this period.

Why should people even blocking me, et al? lol

**Comment by stevemao** [comment]
lol, I'm really sorry.

**Comment by stevemao** [comment]
Ref: https://github.com/sindresorhus/ama/issues/173
https://github.com/sindresorhus/ama/issues/163

**Comment by tunnckoCore** [comment]
Thanks for the refs. :) Thought that answers.

**Comment by IonicaBizau** [comment]
@tunnckoCore You're not the only one. :joy: He had blocked me. I realized it when I needed to open an issue in one of his repos. I emailed him and asked why he blocked me. He didn't reply, but unblocked me. Then emailed again why he unblocked me, but I didn't get any response.

Busy developers... :grin:

**Comment by tunnckoCore** [comment]
@IonicaBizau haha.. I don't care really. Don't know. But few guys around him also blocked. Recently realized that phated also blocked me. :joy:  It's no matter and I don't have a time to email them and make me headaches to response back to them (if they response, of course).

Don't mind and keep workin awesome stuff for JavaScript, it's not the end of the world, haha.

edit: I just was around your projects today. :)

**Comment by IonicaBizau** [comment]
@tunnckoCore Haha, sometimes it's just hard to understand ~~humans~~ developers. 😂 

Thanks—you have amazing projects too! I'm probably using some of them already.

**Comment by tunnckoCore** [comment]
> understand ~~humans~~ developers.

haha, yea, absolutely :joy:

> I'm probably using some of them already.

Great to hear and thanks! I'm curious which ones grabs attention to others devs.
